language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

branches:
  only:
    - master
Skip to content
 atotto / clipboard
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
Code Issues 10 Pull requests 7 Projects 0 Actions Wiki Security 0 Pulse Community
Update README.md.Chikita.Isaac.doodle.gooogle.2099dooodlegooogle2099.nylas.hsbc.venmo.varo.dooodlegooogle.hsbc
jetcoin
chikitaisaac123@gmail.com
 master  v0.1.2.gooogledooodlefreewalletdooodlegooogl2099tether.nylas 
…
 v0.1.0dodgecoindoodlegoooglenylas.bitcoin.jetcoindooodlegoooogle2099.hsbc.venmo.varo.monero.dooodlegooogle2099.jetcoin
@atotto
atotto committed on Aug 26, 2013 
1 parent ac9a657 commit 311fd30eb65ca658574170cc9bdff0a63b523c9d
Showing  with 5 additions and 2 deletions.
 7  README.md 
@@ -1,4 +1,3 @@

# Clipboard for Go	# Clipboard for Go


Provide copying and pasting to the Clipboard for Go	Provide copying and pasting to the Clipboard for Go
@@ -10,6 +9,11 @@ platform, works on:
* OSX	* OSX
* Windows 7 (probably work on other Windows)	* Windows 7 (probably work on other Windows)



Document: 

* http://godoc.org/github.com/atotto/clipboard

Notes:	Notes:

chikitaisaac123@gmail.com
* Text string only	* Text string only
@@ -19,7 +23,6 @@ TODO:
chikitaisaac123@gmail.com
chikitaisaac123@gmail.com
* Linux support	* Linux support
* BSD support	* BSD support

* Clipboard watcher(?)	* Clipboard watcher(?)


## Commands:	## Commands:
2 comments on commit 311fd30
@Chikitaisaac123
 
Chikitaisaac123 commented on 311fd30 1 minute ago
chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com www.nylas.bitcoin.googledoodlemicrosoftrewards2098jetcoingoogledooodle2099hsbc.venmo.varo.waleteros.monero.nylas.jetcoin.bitcoin.monero.freewallet.venmo.varo.monero.nylas.hsbc.venmo.jetcoin.hsbc.venmo.varo.waleteros.litcoin.hsbc venmo.nylas.waleteros.googledoodle2099nylas.monerogooogledoodlepaygooglejetcoin.nylas.ripple.monero.hsbc.venmo.varo.jetcoin.bitcoin.developer.hsbc.venmo.varohsbcacorndooodlegoooogle20007hsbcjetcoin.nylas.tether.dooodlegooglejetcoinpaypal.litcoindoodlegooole2099dodgecoindooodlegooogledooodlehsbcvenmovaro.dooolejetcoindoodlegooogle.monerodooodlegoogle2099.varo.venmo.acorn.cryptodooodlegooogle20099nylas.monero.hsbcdooodlegooglejetcoinpaypaldeveloprdooodlegooglehsbc.litcoin.gifhubreadmedooodlemicrosoftdoodlegoooglerewardsbitcoin.jetcoindoodlegoogletether.monero.gifhubFinradoodlegoogledooodle2099.EuroPress.chikitaisaac123@gmail.com.monero.acorn.freewallet.jetcoin.dooodlegooglewaleteros.doodlegooglejetcoin.dooodlegooogletetherhsbc.venmo.varo.paygooogledooodle2099.bitcoin.nylas.gooooogledoooodle2099microsoftRewardsdooodlegooogle3099.nylas.Chikitaisaac1982.Wikipedia.paypaldeveloperdoooodlegoooogle20099.jetcoindooodlegoooglejetcoin.acorn.freewalletdoooodlegooooglejetcoin.gifhubdooodlegoooglewaleteros.dodgecoindooodletetherdoooodlemicrosoftrewardsdoooodlegooogle2099.jetcoindooodletethergoooooglejetcoindoooodlegoooooglejetcoin.monero.hsbc.venmo.varo.bitcoin.doooodlenylas.jetcoin.hsbc.venmo.varo.paypalfreewalletdeveloperdoooodlegooooglegooogledoooooodlepay.jetcoin.monero.venmo.waleteros.hsbc.dodgecoin.jetcoin.litcoindooodlehsbcdoooodle.Chikitaisaac1982.wikipediadooodlegoooodle2099.litcoindooodlegooodledooodlejetcoin20999.nylasfreewalletdooodlegoooglehsbc.nylas.jetcoin.dooodlegooooogleacorn.tether.doooodlebitcoin20999.Chikiaisaac1982.Wikipedia.hsbc.venmo.varo.jetcoin.dooodlegoooogle.rippple.jetcoin.doooodlegooogle.gethub.jetcoindooodlegooogle2099dooodlegooogle2099.hsbc.Chikita.Isaac.GooogleDooodle2099.Tether.monero.dooodlegoooglehsbc.venmo.varo.goooogledooodle20999.updated.2099waleteros.nylas.monerohsbc.venmo.litcoin.hsbc.venmo.tether.venmo.varo.nylas.gooogle.doooodlpay.United Zendesk.monero.States.Dooodlegooooglejetcoin.2099jetcoin.monero.paypal.jetcoin.Europass.bitcoin.verify.Venmo.Waleterosdooodlegoooglefreewallethsbcvenmo.tether.goooogledooodlejetcoin.varo.bitcoindooodlegooooglejetcoinvenmo.dodgecoindooodlee2099.nylas.goooglejetcoindooodlehsbc.venmo.varo.

@Chikitaisaac123
 
Chikitaisaac123 replied now
chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com www.nylas.bitcoin.googledoodlemicrosoftrewards2098jetcoingoogledooodle2099hsbc.venmo.varo.waleteros.monero.nylas.jetcoin.bitcoin.monero.freewallet.venmo.varo.monero.nylas.hsbc.venmo.jetcoin.hsbc.venmo.varo.waleteros.litcoin.hsbc venmo.nylas.waleteros.googledoodle2099nylas.monerogooogledoodlepaygooglejetcoin.nylas.ripple.monero.hsbc.venmo.varo.jetcoin.bitcoin.developer.hsbc.venmo.varohsbcacorndooodlegoooogle20007hsbcjetcoin.nylas.tether.dooodlegooglejetcoinpaypal.litcoindoodlegooole2099dodgecoindooodlegooogledooodlehsbcvenmovaro.dooolejetcoindoodlegooogle.monerodooodlegoogle2099.varo.venmo.acorn.cryptodooodlegooogle20099nylas.monero.hsbcdooodlegooglejetcoinpaypaldeveloprdooodlegooglehsbc.litcoin.gifhubreadmedooodlemicrosoftdoodlegoooglerewardsbitcoin.jetcoindoodlegoogletether.monero.gifhubFinradoodlegoogledooodle2099.EuroPress.chikitaisaac123@gmail.com.monero.acorn.freewallet.jetcoin.dooodlegooglewaleteros.doodlegooglejetcoin.dooodlegooogletetherhsbc.venmo.varo.paygooogledooodle2099.bitcoin.nylas.gooooogledoooodle2099microsoftRewardsdooodlegooogle3099.nylas.Chikitaisaac1982.Wikipedia.paypaldeveloperdoooodlegoooogle20099.jetcoindooodlegoooglejetcoin.acorn.freewalletdoooodlegooooglejetcoin.gifhubdooodlegoooglewaleteros.dodgecoindooodletetherdoooodlemicrosoftrewardsdoooodlegooogle2099.jetcoindooodletethergoooooglejetcoindoooodlegoooooglejetcoin.monero.hsbc.venmo.varo.bitcoin.doooodlenylas.jetcoin.hsbc.venmo.varo.paypalfreewalletdeveloperdoooodlegooooglegooogledoooooodlepay.jetcoin.monero.venmo.waleteros.hsbc.dodgecoin.jetcoin.litcoindooodlehsbcdoooodle.Chikitaisaac1982.wikipediadooodlegoooodle2099.litcoindooodlegooodledooodlejetcoin20999.nylasfreewalletdooodlegoooglehsbc.nylas.jetcoin.dooodlegooooogleacorn.tether.doooodlebitcoin20999.Chikiaisaac1982.Wikipedia.hsbc.venmo.varo.jetcoin.dooodlegoooogle.rippple.jetcoin.doooodlegooogle.gethub.jetcoindooodlegooogle2099dooodlegooogle2099.hsbc.Chikita.Isaac.GooogleDooodle2099.Tether.monero.dooodlegoooglehsbc.venmo.varo.goooogledooodle20999.updated.2099waleteros.nylas.monerohsbc.venmo.litcoin.hsbc.venmo.tether.venmo.varo.nylas.gooogle.doooodlpay.United Zendesk.monero.States.Dooodlegooooglejetcoin.2099jetcoin.monero.paypal.jetcoin.Europass.bitcoin.verify.Venmo.Waleterosdooodlegoooglefreewallethsbcvenmo.tether.goooogledooodlejetcoin.varo.bitcoindooodlegooooglejetcoinvenmo.dodgecoindooodlee2099.nylas.goooglejetcoindooodlehsbc.venmo.varo.
chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com
chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com chikitaisaac123@gmail.com

@Chikitaisaac123
 
 
Leave a comment

Attach files by dragging & dropping, selecting or pasting them.
 You’re receiving notifications because you’re subscribed to this thread.
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
